### ISSUE TITLE
Detecting groups of consecutives zeros

### ISSUE THREAD

**Issue by JMPivette** [vgXhc/datenecke#1]
Hi,

I was reading your blog and saw this:

> Moving back from the `dupes2` tibble to the counts is not straightforward, as they have different lengths. I can't currently think of a generalizable way to do this. But as I'm only doing with one run, a less elegant way will do.

I did the same kind of analysis few months ago and manage to solve this kind of issue with `rleid()` from {data.table} 

With a dplyr syntax:

```
library(data.table)

counts2 %>% 
  group_by(grp = rleid(Count), 
           location) %>% 
  summarise(start_date = first(Count_Date),
            duration = n(),
            Count = first(Count)) %>% 
  filter(duration  >= 25 & Count == 0)
```

With a data.table syntax:
```
library(data.table)

DTcounts <- data.table(counts2)
consecutive_periods <- DTcounts[, .(start_date = Count_Date[1], 
                                    duration = .N), 
                                by = .(rleid(Count), location, Count)]
consecutive_periods[duration >= 25 & Count == 0]
```

**Comment by vgXhc** [comment]
Thanks, I have to test it, but based on your example this looks much easier!

**Comment by vgXhc** [comment]
Added a section with your code at the end of the post. Thanks again, @JMPivette  

https://datenecke.netlify.com/2020/01/26/bike-counts-temperature-and-precipitation-in-madison-wis/
